version: '3.8'
services:
  db:
    image: mysql
    container_name: timesheet_mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - timesheet_volume:/var/lib/mysql

volumes:
  timesheet_volume:

